export const SET_CACHED_RESPONSE = "SET_CACHED_RESPONSE";
export const SET_FILTERS = "SET_FILTERS";
export const SET_GALLERY = "SET_GALLERY";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_MODAL_ITEM = "SET_MODAL_ITEM";
export const SET_MODAL_ITEM_DETAILS = "SET_MODAL_ITEM_DETAILS";
